version: "3.7"

services:
  web:
    build:
      context: ./web/
    environment:
      - DATABASE_URL=postgresql://miladivm:miladi@db:5432/app_db
    expose:
      - "8000"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web

  db:
    image: postgres:11
    container-name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
